services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/countriesDB
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=development
    volumes:
      - ../app.js:/app/app.js
      - ../src:/app/src
      - ../config:/app/config
      - ../middleware:/app/middleware
      - ../models:/app/models
      - ../routes:/app/routes
      - ../docs:/app/docs
      - ../.env:/app/.env
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
